### ISSUE TITLE
Cannot stop machine from outside

### ISSUE THREAD

**Issue by imaxferrain** [mellonis/turing-machine-js#74]
:'(

**Comment by mellonis** [comment]
@imaxferrain , hi

When you use `run` method, the machine will run synchronously. So you cannot stop machine outside, because the machine is using execution thread already. Apparently.

But, when `runStepByStep` is used, a generator is returned. So, according to spec, you can use `throw` method instead of `next` to stop execution of the machine.

Like that:

```js
const machine = new TuringMachine(/* constructor arguments */);

const executionGenerator = machine.runStepByStep(/* execution arguments */);

executionGenerator.next(); // try make a step

executionGenerator.throw(); // stop execution
```

You can provide `handleState` symbol to the `throw` method of the executionGenerator to provide specific cause of execution stop.
